services:
  teamheart:
    build: .
    container_name: app-teamheart
    env_file:
      - .env
    ports:
      - "8080:8080"
    environment:
      LOGGING_FILE_NAME: /app/logs/teamheart.log
    volumes:
      - teamheart-logs:/app/logs
    networks:
      - teamheart-network
    restart: unless-stopped

volumes:
  teamheart-logs:

networks:
  teamheart-network:
    driver: bridge